[package]
name = "web-socket"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ethers = { version = "2.0", features = ["ws"] }
dotenv = "0.15"
eyre = "0.6"
futures = "0.3"  # ✅ Add this line
