[package]
name = "uniswap"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
