[package]
name = "attacks"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["ws", "rustls"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
eyre = "0.6"
hex = "0.4"
dotenv = "0.15"
