[package]
name = "layer2"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde_json = "1.0"
tui = "0.19"
crossterm = "0.26"
